### PR TITLE
use createPortal with react16

### PR DESCRIPTION
**Pull request by doronbrikman**
This PR adds `createPortal`

Should be answer this #55.
Please let me know if there's anything else to check or to change in this PR.

### CODE REVIEW

**Comment by danreeves** [comment]
Thanks so much! I'll take a look at it ASAP, probably this weekend.

**Comment by danreeves** [comment]
This is looking good so far, just two things:

1. Can we rename `isReact16` to something less version specific, like `hasReactPortal`
2. It currently crashes with an invariant error if you only provide one child.

`Uncaught Error: TetherComponent(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

If you can fix those two issues it'd be great!

**Comment by doronbrikman** [comment]
I fixed it and changed the variable name.
By the way, I'm not so sure the `destroy` function call in the `render` is the best place for it, what do you think?

**Comment by danreeves** [comment]
@doronbrikman Yep, good call. Can we also move the `_createContainer` call from `render` into a constructor?

**Comment by danreeves** [comment]
Thanks for all your work!

**Pull request merged**
