### PR TITLE
Bump Tether to v1.4.3

### PR DESCRIPTION
**Pull request by yasyf**
Includes a bugfix which was making our apps that use react-tether unusable on older Safari versions

### CODE REVIEW

**Comment by yasyf** [comment]
@danreeves test failing with "Error: Authentication failed. Please assign the correct username and access key to the SAUCE_USERNAME and SAUCE_ACCESS_KEY environment variables."

**Comment by danreeves** [comment]
Thanks! Not sure what's wrong with Saucelabs, I'll investigate

**Comment by danreeves** [comment]
Oh, it's just that travis doesn't give external PRs access to the env variables. 

Manually ran tests, LGTM 👍 

Thanks!

**Comment by danreeves** [comment]
Released in 0.6.1 🎉

**Comment by yasyf** [comment]
that Travis thing always gets me. Cheers!

**Pull request merged**
